In [77]:
import numpy as np

In [78]:
# Initialize transition matrix
num_states = 4
num_actions = 3
num_hallucinations = 8
T = np.arange(num_states * num_actions * num_states).reshape(num_states, num_actions, num_states)
T

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [79]:
normalizer = np.sum(T, axis=2, keepdims=True)
normalizer

array([[[  6],
        [ 22],
        [ 38]],

       [[ 54],
        [ 70],
        [ 86]],

       [[102],
        [118],
        [134]],

       [[150],
        [166],
        [182]]])

In [80]:
# Compute normalized T where each row sums to one
T_n = T/normalizer
T_n

array([[[ 0.        ,  0.16666667,  0.33333333,  0.5       ],
        [ 0.18181818,  0.22727273,  0.27272727,  0.31818182],
        [ 0.21052632,  0.23684211,  0.26315789,  0.28947368]],

       [[ 0.22222222,  0.24074074,  0.25925926,  0.27777778],
        [ 0.22857143,  0.24285714,  0.25714286,  0.27142857],
        [ 0.23255814,  0.24418605,  0.25581395,  0.26744186]],

       [[ 0.23529412,  0.24509804,  0.25490196,  0.26470588],
        [ 0.23728814,  0.24576271,  0.25423729,  0.26271186],
        [ 0.23880597,  0.24626866,  0.25373134,  0.26119403]],

       [[ 0.24      ,  0.24666667,  0.25333333,  0.26      ],
        [ 0.24096386,  0.24698795,  0.25301205,  0.25903614],
        [ 0.24175824,  0.24725275,  0.25274725,  0.25824176]]])

In [81]:
# Compute cumulative sums over each entry in each row of T_n
T_cumsum = np.cumsum(T_n, axis=2)
T_cumsum

array([[[ 0.        ,  0.16666667,  0.5       ,  1.        ],
        [ 0.18181818,  0.40909091,  0.68181818,  1.        ],
        [ 0.21052632,  0.44736842,  0.71052632,  1.        ]],

       [[ 0.22222222,  0.46296296,  0.72222222,  1.        ],
        [ 0.22857143,  0.47142857,  0.72857143,  1.        ],
        [ 0.23255814,  0.47674419,  0.73255814,  1.        ]],

       [[ 0.23529412,  0.48039216,  0.73529412,  1.        ],
        [ 0.23728814,  0.48305085,  0.73728814,  1.        ],
        [ 0.23880597,  0.48507463,  0.73880597,  1.        ]],

       [[ 0.24      ,  0.48666667,  0.74      ,  1.        ],
        [ 0.24096386,  0.48795181,  0.74096386,  1.        ],
        [ 0.24175824,  0.48901099,  0.74175824,  1.        ]]])

In [82]:
# Pre-generate random state index array
S = np.random.randint(num_states, size=num_hallucinations)
S

array([3, 3, 2, 0, 3, 3, 2, 3])

In [83]:
# Pre-generate random action index array
A = np.random.randint(num_actions, size=num_hallucinations)
A

array([2, 1, 2, 2, 2, 0, 1, 1])

In [84]:
# Get random states by using S as an index array to T_cumsum
random_state_T = T_cumsum[S]
random_state_T

array([[[ 0.24      ,  0.48666667,  0.74      ,  1.        ],
        [ 0.24096386,  0.48795181,  0.74096386,  1.        ],
        [ 0.24175824,  0.48901099,  0.74175824,  1.        ]],

       [[ 0.24      ,  0.48666667,  0.74      ,  1.        ],
        [ 0.24096386,  0.48795181,  0.74096386,  1.        ],
        [ 0.24175824,  0.48901099,  0.74175824,  1.        ]],

       [[ 0.23529412,  0.48039216,  0.73529412,  1.        ],
        [ 0.23728814,  0.48305085,  0.73728814,  1.        ],
        [ 0.23880597,  0.48507463,  0.73880597,  1.        ]],

       [[ 0.        ,  0.16666667,  0.5       ,  1.        ],
        [ 0.18181818,  0.40909091,  0.68181818,  1.        ],
        [ 0.21052632,  0.44736842,  0.71052632,  1.        ]],

       [[ 0.24      ,  0.48666667,  0.74      ,  1.        ],
        [ 0.24096386,  0.48795181,  0.74096386,  1.        ],
        [ 0.24175824,  0.48901099,  0.74175824,  1.        ]],

       [[ 0.24      ,  0.48666667,  0.74      ,  1.        ]

In [85]:
# Get random actions by using A as an index array to random_state_T
# We want to index each random state so we use arange to index all rows in random_state_T
random_action_T = random_state_T[np.arange(num_hallucinations), A]
random_action_T

array([[ 0.24175824,  0.48901099,  0.74175824,  1.        ],
       [ 0.24096386,  0.48795181,  0.74096386,  1.        ],
       [ 0.23880597,  0.48507463,  0.73880597,  1.        ],
       [ 0.21052632,  0.44736842,  0.71052632,  1.        ],
       [ 0.24175824,  0.48901099,  0.74175824,  1.        ],
       [ 0.24      ,  0.48666667,  0.74      ,  1.        ],
       [ 0.23728814,  0.48305085,  0.73728814,  1.        ],
       [ 0.24096386,  0.48795181,  0.74096386,  1.        ]])

In [86]:
# Generate random samples of states to transition to as 2d array with one column
# Each entry represents a random selection of the next state
samples = np.random.random_sample(num_hallucinations).reshape(num_hallucinations, 1)
samples

array([[ 0.30257022],
       [ 0.92192204],
       [ 0.3301367 ],
       [ 0.48714274],
       [ 0.82256997],
       [ 0.25315227],
       [ 0.12019529],
       [ 0.25365512]])

In [87]:
# Create boolean array where random_action_T less than samples
boolean_array = random_action_T < samples
boolean_array

array([[ True, False, False, False],
       [ True,  True,  True, False],
       [ True, False, False, False],
       [ True,  True, False, False],
       [ True,  True,  True, False],
       [ True, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]], dtype=bool)

In [88]:
# The boolean array represents the selection of the next state s' based on the probabilities.
# The trick here is that booleans can be summed!  False = 0 and True = 1
# The sums reprensent the index for each row which represents the next state s'.
S_prime = boolean_array.sum(axis=1)
S_prime

array([1, 3, 1, 2, 3, 1, 0, 1])

In [89]:
# The other way would be to use np.random.choice
# Problem 1:  np.random.choice is slow
# Problem 2:  np.random.choice can't be vectorized.  
#             You have to call random choice for each set of probabilities per transition.  This means a for loop!
p = T[S, A] / T[S, A].sum(axis=1, keepdims=True)
print(p)
print(p[0])

[[ 0.24175824  0.24725275  0.25274725  0.25824176]
 [ 0.24096386  0.24698795  0.25301205  0.25903614]
 [ 0.23880597  0.24626866  0.25373134  0.26119403]
 [ 0.21052632  0.23684211  0.26315789  0.28947368]
 [ 0.24175824  0.24725275  0.25274725  0.25824176]
 [ 0.24        0.24666667  0.25333333  0.26      ]
 [ 0.23728814  0.24576271  0.25423729  0.26271186]
 [ 0.24096386  0.24698795  0.25301205  0.25903614]]
[ 0.24175824  0.24725275  0.25274725  0.25824176]


In [90]:
S_prime_alt =  np.zeros(num_hallucinations, dtype=int)
for i in range(num_hallucinations):
    S_prime_alt[i] =  np.random.choice(4, p=p[i])
S_prime_alt

array([1, 2, 2, 3, 3, 0, 0, 2])